### ISSUE TITLE
casac build dependencies not working on osx 10.11.6

### ISSUE THREAD

**Issue by caseyjlaw** [pkgw/pwkit#4]
Starting with a fresh conda environment on the OSX... Installing casac via new pkgw-forge (with boost from conda-forge) leads to the common "No module named _atmosphere" import error:

```(test) MacBook-Pro:~ caseyjlaw$ uname -a
Darwin MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

MacBook-Pro:~ caseyjlaw$ conda create -n test -c pkgw-forge numpy jupyter pwkit casa-tools casa-python casa-data
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/caseyjlaw/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    qtconsole-4.2.1            |           py27_1         148 KB

The following NEW packages will be INSTALLED:

    _nb_ext_conf:       0.3.0-py27_0                    
    anaconda-client:    1.6.0-py27_0                    
    appnope:            0.1.0-py27_0                    
    backports:          1.0-py27_0                      
    backports_abc:      0.5-py27_0                      
    boost:              1.57.0-4                        
    casa-data:          r10954-1       pkgw-forge       
    casa-nrao-casacore: 4.6.0-2        pkgw-forge       
    casa-python:        4.6.0-py27_3   pkgw-forge       
    casa-tools:         4.6.0-4        pkgw/channel/main
    cfitsio:            3.370-3        pkgw/channel/main
    clyent:             1.2.2-py27_0                    
    configparser:       3.5.0-py27_0                    
    dbus-client:        1.10.10-0      pkgw/channel/main
    dbus-cxx:           0.9.1-1        pkgw/channel/main
    decorator:          4.0.10-py27_1                   
    entrypoints:        0.2.2-py27_0                    
    enum34:             1.1.6-py27_0                    
    expat:              2.1.0-2        pkgw/channel/main
    fftw:               3.3.4-3        pkgw/channel/main
    functools32:        3.2.3.2-py27_0                  
    get_terminal_size:  1.0.0-py27_0                    
    gettext:            0.19.6-2       pkgw/channel/main
    glib:               2.46.2-5       pkgw/channel/main
    gsl:                2.2.1-0        pkgw/channel/main
    hdf5:               1.8.17-1                        
    icu:                54.1-0                          
    ipykernel:          4.5.2-py27_0                    
    ipython:            5.1.0-py27_1                    
    ipython_genutils:   0.1.0-py27_0                    
    ipywidgets:         5.2.2-py27_0                    
    jbig:               2.1-0                           
    jinja2:             2.8-py27_1                      
    jpeg:               8d-2                            
    jsonschema:         2.5.1-py27_0                    
    jupyter:            1.0.0-py27_3                    
    jupyter_client:     4.4.0-py27_0                    
    jupyter_console:    5.0.0-py27_0                    
    jupyter_core:       4.2.1-py27_0                    
    libffi32:           3.2.1-1        pkgw/channel/main
    libiconv:           1.14-0                          
    libpng:             1.6.22-0                        
    libsakura:          2.0.0-1        pkgw-forge       
    libtiff:            4.0.6-2                         
    libxml2:            2.9.4-0                         
    libxslt:            1.1.28-3                        
    markupsafe:         0.23-py27_2                     
    mistune:            0.7.3-py27_1                    
    mkl:                11.3.3-0                        
    modern-xorg-stack:  2016.03-1      pkgw-forge       
    nb_anacondacloud:   1.2.0-py27_0                    
    nb_conda:           2.0.0-py27_0                    
    nb_conda_kernels:   2.0.0-py27_0                    
    nbconvert:          4.2.0-py27_0                    
    nbformat:           4.2.0-py27_0                    
    nbpresent:          3.0.2-py27_0                    
    ncurses:            5.9-10                          
    notebook:           4.3.0-py27_0                    
    numpy:              1.11.2-py27_0                   
    openssl:            1.0.2j-0                        
    path.py:            8.2.1-py27_0                    
    pathlib:            1.0.1-py27_1   pkgw/channel/main
    pathlib2:           2.1.0-py27_0                    
    pexpect:            4.0.1-py27_0                    
    pgplot:             5.2.2-9        pkgw-forge       
    pickleshare:        0.7.4-py27_0                    
    pip:                9.0.1-py27_1                    
    prompt_toolkit:     1.0.9-py27_0                    
    ptyprocess:         0.5.1-py27_0                    
    pwkit:              0.8.4-py27_1   pkgw-forge       
    pygments:           2.1.3-py27_0                    
    pyqt:               5.6.0-py27_1                    
    python:             2.7.13-0                        
    python-dateutil:    2.6.0-py27_0                    
    pytz:               2016.10-py27_0                  
    pyyaml:             3.12-py27_0                     
    pyzmq:              16.0.2-py27_0                   
    qt:                 5.6.2-0                         
    qt4dbus:            4.8.7-py27_0   pkgw-forge       
    qtconsole:          4.2.1-py27_1                    
    qwt5:               5.2.3-2        pkgw-forge       
    readline:           6.2-2                           
    requests:           2.12.4-py27_0                   
    rpfits:             2.23-6         pkgw-forge       
    setuptools:         27.2.0-py27_0                   
    simplegeneric:      0.8.1-py27_1                    
    singledispatch:     3.4.0.3-py27_0                  
    sip:                4.18-py27_0                     
    six:                1.10.0-py27_0                   
    sqlite:             3.13.0-0                        
    ssl_match_hostname: 3.4.0.2-py27_1                  
    terminado:          0.6-py27_0                      
    tk:                 8.5.18-0                        
    tornado:            4.4.2-py27_0                    
    traitlets:          4.3.1-py27_0                    
    wcslib:             5.12-4         pkgw-forge       
    wcwidth:            0.1.7-py27_0                    
    wheel:              0.29.0-py27_0                   
    widgetsnbextension: 1.2.6-py27_0                    
    xerces-c28:         2.8.0-2        pkgw/channel/main
    xz:                 5.2.2-0                         
    yaml:               0.1.6-0                         
    zlib:               1.2.8-3                         

Proceed ([y]/n)? 

Pruning fetched packages from the cache ...
Fetching packages ...
qtconsole-4.2. 100% |##############################################################################################################################| Time: 0:00:00   1.08 MB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

MacBook-Pro:~ caseyjlaw$ source activate test
(test) MacBook-Pro:~ caseyjlaw$ conda install -c conda-forge boost
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/caseyjlaw/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freetype-2.6.3             |                1         782 KB  conda-forge
    qtconsole-4.2.1            |           py27_1         133 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         914 KB

The following NEW packages will be INSTALLED:

    freetype:          2.6.3-1      conda-forge      
    qt-dbus-component: 4.8.7-2      pkgw/channel/main

The following packages will be UPDATED:

    boost:             1.57.0-4                       --> 1.62.0-py27_0 conda-forge      
    icu:               54.1-0                         --> 56.1-4        conda-forge      

The following packages will be SUPERCEDED by a higher-priority channel:

    pyqt:              5.6.0-py27_1                   --> 4.11.4-py27_2 conda-forge      
    qtconsole:         4.2.1-py27_1                   --> 4.2.1-py27_1  conda-forge      

The following packages will be DOWNGRADED due to dependency conflicts:

    casa-tools:        4.6.0-4      pkgw/channel/main --> 4.5-1         pkgw/channel/main
    qt:                5.6.2-0                        --> 4.8.7-4                        

Proceed ([y]/n)? 

Pruning fetched packages from the cache ...
Fetching packages ...
freetype-2.6.3 100% |##############################################################################################################################| Time: 0:00:06 119.67 kB/s
qtconsole-4.2. 100% |##############################################################################################################################| Time: 0:00:01  78.46 kB/s
Extracting packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#################################################################################################################################################| 100%
(test) MacBook-Pro:~ caseyjlaw$ 
(test) MacBook-Pro:~ caseyjlaw$ python -c 'import casac'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/caseyjlaw/miniconda/envs/test/lib/python2.7/site-packages/casac.py", line 1, in <module>
    import __casac__
  File "/Users/caseyjlaw/miniconda/envs/test/lib/python2.7/site-packages/__casac__/__init__.py", line 49, in <module>
    import atmosphere
  File "/Users/caseyjlaw/miniconda/envs/test/lib/python2.7/site-packages/__casac__/atmosphere.py", line 21, in <module>
    _atmosphere = swig_import_helper()
  File "/Users/caseyjlaw/miniconda/envs/test/lib/python2.7/site-packages/__casac__/atmosphere.py", line 20, in swig_import_helper
    return importlib.import_module('_atmosphere')
  File "/Users/caseyjlaw/miniconda/envs/test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _atmosphere
```

**Comment by pkgw** [comment]
Uggghhhh. Sorry that this is being so obnoxious. But, I'm getting the hang of how all of the pieces fit together. I think I've fixed the Linux packages, and I will work on OSX packages.

**Comment by pkgw** [comment]
Uploaded some new package last night. Hopefully it works now.

**Comment by pkgw** [comment]
Looking at the above installation, though, there should be a *lot* of packages coming from the `conda-forge` channel, and none from the plain `pkgw` channel. In the environment in which the installation of the packages is happening, the output of the `conda info` command should include something like:

```
 channel URLs :           https://conda.anaconda.org/pkgw-forge/osx-64
                          https://conda.anaconda.org/pkgw-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by caseyjlaw** [comment]
Confirmed! Can run basic analysis on OSX now.
Updated my installation instructions at https://github.com/caseyjlaw/rtpipe to use conda-forge channel for basic scientific Python stuff, then pkgw channel for pwkit and CASA stuff. Then its just `pip install rtpipe`.
